local heaps = require("thoth.core.heaps")

local minHeap = heaps.newMinHeap()
minHeap:push(5)
minHeap:push(1)
minHeap:push(3)
assert(minHeap:pop() == 1)
assert(minHeap:pop() == 3)
assert(minHeap:pop() == 5)

local pq = heaps.newPriorityQueue()
pq:push("low", 10)
pq:push("high", 1)
assert(pq:pop() == "high")
assert(pq:pop() == "low")
