local sets = require("thoth.core.sets")
local deques = require("thoth.core.deques")
local ringbuffers = require("thoth.core.ringbuffers")
local orderedmaps = require("thoth.core.orderedmaps")
local unionfind = require("thoth.core.unionfind")

local a = sets.new({"a", "b"})
local b = sets.new({"b", "c"})
assert(a:has("a"))
assert(a:union(b):size() == 3)
assert(a:intersection(b):has("b"))
assert(not a:difference(b):has("b"))

local deque = deques.new()
deque:pushBack(2):pushFront(1):pushBack(3)
assert(deque:peekFront() == 1)
assert(deque:peekBack() == 3)
assert(deque:popFront() == 1)
assert(deque:popBack() == 3)
assert(deque:size() == 1)

local ring = ringbuffers.new(3)
ring:push(1):push(2):push(3):push(4)
local values = ring:values()
assert(#values == 3)
assert(values[1] == 2 and values[3] == 4)
assert(ring:isFull())

local map = orderedmaps.new()
map:set("a", 1):set("b", 2):set("a", 3)
assert(map:get("a") == 3)
assert(map:keys()[1] == "a" and map:keys()[2] == "b")
assert(map:remove("a") == 3)
assert(not map:has("a"))

local uf = unionfind.new({"a", "b", "c"})
uf:union("a", "b")
assert(uf:connected("a", "b"))
assert(not uf:connected("a", "c"))
assert(type(uf:groups()) == "table")
