local objRoot = "addons/kaykit_dungeon_remastered/Assets/obj/"

local function obj(name)
    return objRoot .. name
end

return {
    source = {
        pack = "KayKit Dungeon Remastered",
        url = "https://github.com/KayKit-Game-Assets/KayKit-Dungeon-Remastered-1.0",
        author = "Kay Lousberg / KayKit",
        license = "CC0 1.0 Universal",
        texture = "addons/kaykit_dungeon_remastered/Assets/texture/dungeon_texture.png",
    },
    tiles = {
        archive_floor = { path = obj("floor_tile_large.obj"), role = "base_floor" },
        archive_wall = { path = obj("wall_shelves.obj"), role = "base_wall" },
        corridor = { path = obj("floor_tile_small.obj"), role = "base_floor" },
        salt_floor = { path = obj("floor_tile_big_grate.obj"), role = "base_floor" },
        salt_wall = { path = obj("wall_window_closed.obj"), role = "base_wall" },
        salt_causeway = { path = obj("floor_foundation_front_and_sides.obj"), role = "base_floor" },
        brine_pool = { path = obj("floor_tile_big_grate_open.obj"), role = "blocked_floor" },
        ember_floor = { path = obj("floor_tile_small_broken_A.obj"), role = "base_floor" },
        ember_wall = { path = obj("wall_cracked.obj"), role = "base_wall" },
        ember_corridor = { path = obj("floor_dirt_large_rocky.obj"), role = "base_floor" },
        ash_choke = { path = obj("rubble_large.obj"), role = "blocked_prop" },
        sealed_door = { path = obj("wall_doorway_door.obj"), role = "blocked_wall" },
        camp_marker = { path = obj("candle_lit.obj"), role = "curio_prop" },
        relic_cache = { path = obj("chest_gold.obj"), role = "curio_prop" },
        whispering_idol = { path = obj("pillar_decorated.obj"), role = "curio_prop" },
        wire_snare = { path = obj("spikes.obj"), role = "curio_prop" },
        salt_font = { path = obj("barrel_large_decorated.obj"), role = "curio_prop" },
        brine_lockbox = { path = obj("chest.obj"), role = "curio_prop" },
        ash_vent = { path = obj("floor_tile_grate_open.obj"), role = "curio_floor" },
        ember_reliquary = { path = obj("chest_gold_lid.obj"), role = "curio_prop" },
        lost_page = { path = obj("table_small_decorated_A.obj"), role = "curio_prop" },
        sealed_name = { path = obj("key.obj"), role = "curio_prop" },
        false_index = { path = obj("shelves.obj"), role = "curio_prop" },
        page_bearer = { path = obj("shelf_small.obj"), role = "curio_prop" },
        misfiled_dead = { path = obj("bed_floor.obj"), role = "curio_prop" },
        witness_drawer = { path = obj("trunk_medium_A.obj"), role = "curio_prop" },
        clerk_cocoon = { path = obj("barrel_large.obj"), role = "curio_prop" },
        name_press = { path = obj("table_medium.obj"), role = "curio_prop" },
        open_register = { path = obj("table_medium_decorated_A.obj"), role = "curio_prop" },
        stamped_confessional = { path = obj("wall_arched.obj"), role = "curio_prop" },
        tide_valve = { path = obj("keg_decorated.obj"), role = "curio_prop" },
        salt_register = { path = obj("table_medium_tablecloth_decorated_B.obj"), role = "curio_prop" },
        tov_child = { path = obj("bed_decorated.obj"), role = "curio_prop" },
        deep_sluice_key = { path = obj("keyring.obj"), role = "curio_prop" },
        shutoff_shrine = { path = obj("pillar.obj"), role = "curio_prop" },
        silted_cradle = { path = obj("bed_frame.obj"), role = "curio_prop" },
        pressure_bell = { path = obj("keyring_hanging.obj"), role = "curio_prop" },
        brine_reliquary = { path = obj("chest_gold.obj"), role = "curio_prop" },
        ember_ward = { path = obj("banner_patternA_red.obj"), role = "curio_prop" },
        ash_name = { path = obj("plate_small.obj"), role = "curio_prop" },
        warm_ledger = { path = obj("table_small_decorated_B.obj"), role = "curio_prop" },
        aron_boy = { path = obj("bed_floor.obj"), role = "curio_prop" },
        white_furnace_key = { path = obj("key.obj"), role = "curio_prop" },
        false_vow = { path = obj("banner_patternC_red.obj"), role = "curio_prop" },
        ash_lung_reliquary = { path = obj("chest.obj"), role = "curio_prop" },
        fuse_saint = { path = obj("candle_triple.obj"), role = "curio_prop" },
        halo_vent = { path = obj("floor_tile_extralarge_grates_open.obj"), role = "curio_floor" },
        vitrified_cot = { path = obj("bed_frame.obj"), role = "curio_prop" },
        boss_sigil = { path = obj("floor_tile_small_decorated.obj"), role = "encounter_marker" },
        tide_sigil = { path = obj("floor_tile_big_grate.obj"), role = "encounter_marker" },
        ember_sigil = { path = obj("floor_tile_big_spikes.obj"), role = "encounter_marker" },
        exit_gate = { path = obj("wall_gated.obj"), role = "exit_gate" },
        black_water = { path = obj("floor_tile_extralarge_grates_open.obj"), role = "blocked_floor" },
    },
}
