return {
    fadeSeconds = 1.6,
    contexts = {
        title = "estate",
        settings = "estate",
        estate = "estate",
        journal = "estate",
        expedition = "expedition_calm",
        expedition_tense = "expedition_tense",
        combat = "combat_normal",
        boss = "combat_boss",
        victory = "victory_sting",
        gameover = "death_sting",
        credits = "credits",
    },
    tracks = {
        estate = {
            title = "Old Money Estate",
            creator = "Shorts_by_PazuzuStudio",
            path = "assets/music/estate.mp3",
            source = "https://pixabay.com/music/modern-classical-old-money-estate-534048/",
            license = "Pixabay Content License",
            certificate = "assets/music/licenses/estate.txt",
            loop = true,
        },
        expedition_calm = {
            title = "Dark Fantasy Ambient (Dungeon Synth)",
            creator = "DeusLower",
            path = "assets/music/expedition_calm.mp3",
            source = "https://pixabay.com/music/ambient-dark-fantasy-ambient-dungeon-synth-248213/",
            license = "Pixabay Content License",
            certificate = "assets/music/licenses/expedition_calm.txt",
            loop = true,
        },
        expedition_tense = {
            title = "Tense Horror Background",
            creator = "Universfield",
            path = "assets/music/expedition_tense.mp3",
            source = "https://pixabay.com/music/mystery-tense-horror-background-174809/",
            license = "Pixabay Content License",
            certificate = "assets/music/licenses/expedition_tense.txt",
            loop = true,
        },
        combat_normal = {
            title = "Battle - Battle Music",
            creator = "PaulYudin",
            path = "assets/music/combat_normal.mp3",
            source = "https://pixabay.com/music/adventure-battle-battle-music-491417/",
            license = "Pixabay Content License",
            certificate = "assets/music/licenses/combat_normal.txt",
            loop = true,
        },
        combat_boss = {
            title = "Dark Epic",
            creator = "NastelBom",
            path = "assets/music/combat_boss.mp3",
            source = "https://pixabay.com/music/adventure-dark-epic-487720/",
            license = "Pixabay Content License",
            certificate = "assets/music/licenses/combat_boss.txt",
            loop = true,
        },
        victory_sting = {
            title = "Victory",
            creator = "NastelBom",
            path = "assets/music/victory_sting.mp3",
            source = "https://pixabay.com/music/main-title-victory-400621/",
            license = "Pixabay Content License",
            certificate = "assets/music/licenses/victory_sting.txt",
            loop = false,
        },
        death_sting = {
            title = "Evil organ sting (Medium)",
            creator = "Cartoon-Music-Game-Sfx",
            path = "assets/music/death_sting.mp3",
            source = "https://pixabay.com/music/horror-scene-evil-organ-sting-medium-529241/",
            license = "Pixabay Content License",
            certificate = "assets/music/licenses/death_sting.txt",
            loop = false,
        },
        credits = {
            title = "Ambient Cinematic",
            creator = "AtlasAudio",
            path = "assets/music/credits.mp3",
            source = "https://pixabay.com/music/ambient-ambient-cinematic-510518/",
            license = "Pixabay Content License",
            certificate = "assets/music/licenses/credits.txt",
            loop = true,
        },
    },
}
